import { fileURLToPath } from 'node:url'
import vue from '@vitejs/plugin-vue'
import type { StorybookConfig } from '@storybook/vue3-vite'

const repoRoot = new URL('../../../', import.meta.url)

/** The theme's components import the VitePress client runtime, which only
 *  exists inside a running site. Storybook serves the same harness the unit
 *  tests use so every component can be mounted in isolation. */
const vitepressHarness = fileURLToPath(
  new URL('shared/vitepress-harness/module.ts', repoRoot)
)

/** `@localSearchIndex` is generated by VitePress from the built site. */
const localSearchIndex = fileURLToPath(
  new URL('shared/vitepress-harness/local-search-index.ts', repoRoot)
)

const config: StorybookConfig = {
  stories: ['../src/**/*.mdx', '../src/**/*.stories.@(ts|js)'],
  addons: ['@storybook/addon-docs', '@storybook/addon-a11y'],
  framework: {
    name: '@storybook/vue3-vite',
    options: {}
  },
  core: {
    disableTelemetry: true
  },
  // Relative asset URLs so the built Storybook works wherever it is mounted
  // (GitHub Pages serves it from `/storybook/`).
  viteFinal: (viteConfig) => ({
    ...viteConfig,
    base: './',
    // Compile-time flags VitePress injects from the site config. The search
    // and ads integrations read them at module scope.
    define: {
      ...viteConfig.define,
      __VP_LOCAL_SEARCH__: 'true',
      __ALGOLIA__: 'false',
      __CARBON__: 'false',
      __VUE_PROD_DEVTOOLS__: 'false'
    },
    // Stories import theme SFCs straight from source, outside this package's
    // own dependency graph, so the Vue plugin is registered explicitly.
    plugins: [...(viteConfig.plugins ?? []), vue()],
    resolve: {
      ...viteConfig.resolve,
      alias: [
        ...(Array.isArray(viteConfig.resolve?.alias)
          ? viteConfig.resolve.alias
          : []),
        { find: /^vitepress$/, replacement: vitepressHarness },
        { find: /^@localSearchIndex$/, replacement: localSearchIndex }
      ]
    },
    server: {
      ...viteConfig.server,
      fs: {
        ...viteConfig.server?.fs,
        // Stories import theme sources and the harness from outside this package.
        allow: [fileURLToPath(repoRoot)]
      }
    }
  })
}

export default config
