# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node_version: ['20.19.0', '22.18.0', '24']

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Vite+
        uses: voidzero-dev/setup-vp@624fe22ccfe9204a526ac8139186d34297453722 # v1
        with:
          node-version: ${{ matrix.node_version }}
          cache: true
          run-install: false

      - name: Install dependencies
        run: vp install --frozen-lockfile

      - name: Run checks
        if: matrix.node_version != '20.19.0'
        run: vp check --fix

      - name: Run tests
        run: vp run test

      - name: Build
        run: vp run build
